[colors]
background = "#f9f9f9"
foreground = "#1f1f1f"
cursor     = "#7f7f7f"

selection-background = "#4688db"
selection-foreground = "#1f1f1f"

black = "#606060"
red = "#f90000"
green = "#9fcf20"
yellow = "#df9f00"
blue = "#5999e9"
magenta = "#7f7fef"
cyan = "#9fefcf"
white = "#ffffff"

light-black = "#7f7f7f"
light-red = "#f90000"
light-green = "#7faf00"
light-yellow = "#dfa900"
light-blue = "#5999e9"
light-magenta = "#af69cf"
light-cyan = "#9fefcf"
light-white = "#ffffff"
